name: Build the SDK with Unreal

on:
  #pull_request:
    #branches: # Made towards the following
    #  - main
    #  - release/*
    #  - dev*
    #types: # Only on the following activity
    #  - opened
    #  - synchronize # Changes to the branch like new commits, ammends, etc.
    #  - reopened
    #  - unlocked
  push:
    branches: # Made towards the following
      - ci/*
    #  - main
    #  - dev
    #tags:
    #  - v**

jobs:
  build:
    name: Unreal Engine version ${{matrix.unrealVersion}}
    runs-on: ubuntu-latest
    container: epicgames/unrealengine:dev-${{env.EngineVersion}}
    strategy:
      fail-fast: false
      matrix:
        unrealVersion:
          - 4.27.2
          - 5.0.3
          - 5.1.1
    env:
      EngineVersion: "${{matrix.unrealVersion}}"

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2

      - name: Add Engine version to uplugin
        run: shortEngineVersion=" ${{env.EngineVersion}}" && shortEngineVersion="${shortEngineVersion%.*}" && insertString="\"EngineVersion\":${shortEngineVersion}," && sed -i "6i\  \  $insertString" ./LootLockerSDK/LootLockerSDK.uplugin

      #- name: Create Dockerfile in place
      #  run: |
      #    sdkDirectory=$(pwd)
      #    echo "FROM ghcr.io/epicgames/unreal-engine:dev-${{env.EngineVersion}}" >> ../Dockerfile
      #    echo "" >> ../Dockerfile
      #    echo "WORKDIR /LootLockerSDK" >> ../Dockerfile
      #    echo "" >> ../Dockerfile
      #    echo "COPY $sdkDirectory/LICENSE LICENSE" >> ../Dockerfile
      #    echo "COPY $sdkDirectory/README.md README.md" >> ../Dockerfile
      #    echo "COPY $sdkDirectory/LootLockerSDK/Config LootLockerSDK/Config" >> ../Dockerfile
      #    echo "COPY $sdkDirectory/LootLockerSDK/Resources LootLockerSDK/Resources" >> ../Dockerfile
      #    echo "COPY $sdkDirectory/LootLockerSDK/Source LootLockerSDK/Source" >> ../Dockerfile
      #    echo "COPY $sdkDirectory/LootLockerSDK/LootLockerSDK.uplugin LootLockerSDK/LootLockerSDK.uplugin" >> ../Dockerfile
      #    echo "" >> ../Dockerfile
      #    echo "COPY . .
      #    echo "RUN cat /LootLockerSDK/LootLockerSDK/LootLockerSDK.uplugin"
      #    cat ../Dockerfile

      #- name: Launch Unreal Engine in container
      #  run: |
      #    docker build -t local < ../Dockerfile
      #    docker run -it -v 

      